### ISSUE TITLE
Configuration details，If the content to be published is empty, it cannot be published

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#101]
配置数据为空/配置未发生变化时，点击“发布”按钮，应提示用户“暂无可发布的配置”；
现可发布成功，配置数据为空

![image](https://user-images.githubusercontent.com/95004531/174220102-9924add7-97c2-4bda-8401-c0343b00cf13.png)

**Comment by codding-y** [comment]
已经改成在点击发布按钮时 提示：配置对象内容没有变化

**Comment by LazyEar0** [comment]
配置数据为空时不做限制，可正常发布
