### ISSUE TITLE
Configuration details . An error is reported when entering the service configuration details

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#238]
成功克隆Biz的配置对象至新增加的项目，第一次进入新增加的项目业务配置详情报错
![image](https://user-images.githubusercontent.com/95004531/197478296-d9fd716f-3fbf-4b92-9f83-946d24bc3588.png)
![image](https://user-images.githubusercontent.com/95004531/197478526-ca74ab14-34d3-4431-a5cc-9777a2994231.png)

**Comment by codding-y** [comment]
未复现

**Comment by codding-y** [comment]
是加密配置的问题
