### ISSUE TITLE
Clone the configuration object. The Select All button is incorrect

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#267]
全选按钮错误
![image](https://user-images.githubusercontent.com/95004531/200981540-23f6d23d-9fb6-4468-a035-9aa6e8f99414.png)

**Comment by codding-y** [comment]
未复现

**Comment by codding-y** [comment]
未复现，可以提供详细的操作步骤：业务配置？克隆到其他应用？

**Comment by LazyEar0** [comment]
克隆APP所有应用 - 克隆到其他应用 - 逐一勾选配置对象，配置对象全部选中后，全选按钮没有被选中
