### ISSUE TITLE
Release history in non-properties format should not be awakened by clicking on the All configured input box

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#295]
非Properties格式的发布历史，点击全部配置的输入框，应不会被唤醒，现边框会变成主题色
![image](https://user-images.githubusercontent.com/95004531/210943598-b450bedb-fc18-44b6-8c3f-f3400bbfaff6.png)

**Comment by codding-y** [comment]
组件正常功能，现在是readonly。是可以滚动和放大输入框的，如果禁用就不能滚动和放大输入框了，会导致内容看不全。
