### ISSUE TITLE
After the token expires, user data cannot be obtained

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#296]
token过期后，获取不到用户数据
![image](https://user-images.githubusercontent.com/95004531/210945694-38a6c138-1740-479d-a1a1-379eed89a1e8.png)

**Comment by codding-y** [comment]
这个用户就叫empty，auth之前会默认创建一个用户叫empty。现在不知道叫什么。

**Comment by codding-y** [comment]
已解决
