### ISSUE TITLE
Add the clone function to a public configuration object

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#313]
公共配置对象增加克隆功能，仅可克隆至当前公共配置对象的其他集群。

**Comment by zyz** [comment]
#373 public configuration, only other clisters of the currently configured object

**Comment by LazyEar0** [comment]
待代码合并后，回归此问题

**Comment by LazyEar0** [comment]
单独配置对象克隆和批量克隆都需要

**Comment by zyz** [comment]
#390 puiblic config add clone all
