### ISSUE TITLE
In the full-screen popover, after you close the error dialog box, the full-screen popover will also be closed

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#331]
在全屏弹窗下，触发错误提示，点击提示框的“close”按钮。整个全屏弹窗会被关闭，应仅关闭提示框。
![image](https://user-images.githubusercontent.com/95004531/218658790-1dd833ce-6d17-4923-a4c4-c9737a31ed96.png)

**Comment by kogel-net** [comment]
#337 the component package has been updated and this bug has been fixed

**Comment by LazyEar0** [comment]
@kogel-net  点击提示框，会触发关闭全屏弹窗操作。
![image](https://user-images.githubusercontent.com/95004531/223628526-12d41510-8ad7-42ec-87cb-fe27eb7750e5.png)
