### ISSUE TITLE
The translation of the text to undo the popover of the configuration object is incorrect in English. Procedure

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#332]
英文状态下，撤销配置对象弹窗的文本与中文的文本描述不匹配，部分文本没有被翻译
![image](https://user-images.githubusercontent.com/95004531/218659389-746806e7-7ca3-4091-b0e2-d8d7ddc94bc3.png)
![image](https://user-images.githubusercontent.com/95004531/218659563-746b6e63-9239-4f45-831c-8bc368d358db.png)

**Comment by zyz** [comment]
#346 Keys separated by English dot get last, configure the English languag

**Comment by LazyEar0** [comment]
@zyz  此问题仍存在
