### ISSUE TITLE
When clone configuration objects conflict in English, the translation of some text prompted at the bottom is missing.

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#333]
英文状态下，克隆配置对象冲突时，底部提示的部分文本翻译缺失。
![image](https://user-images.githubusercontent.com/95004531/218675113-446e246a-5413-48e0-ab0f-fb31cb89b70b.png)
![image](https://user-images.githubusercontent.com/95004531/218675159-296fd2bc-d2fa-4bbb-9b15-4ad190df5db7.png)

**Comment by xyfy** [comment]
Resolved in #346
