### ISSUE TITLE
Switching to Panorama, the cluster will flash

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#367]
切换至全景，集群处会出现闪动

https://user-images.githubusercontent.com/95004531/222664751-be2ff867-a845-4127-af48-184c2c57039e.mp4

**Comment by binwan-dev** [comment]
Same issue. [433](https://github.com/masastack/MASA.DCC/issues/433)

**Comment by LazyEar0** [comment]
重复
