### ISSUE TITLE
DCC综合配置中，项目类型配置修改

### ISSUE THREAD

**Issue by xie1wei2** [masastack/MASA.DCC#394]
![企业微信截图_16784349116885](https://user-images.githubusercontent.com/101324746/224257065-c250293b-2354-41b9-9bbb-77043ff3a5bf.png)
1.显示名称这里可以设置中间的空格，前后默认空格不生效

**Comment by doddgu** [comment]
@codding-y PTAL

**Comment by codding-y** [comment]
@LazyEar0 Please confirm the specific requirements

**Comment by LazyEar0** [comment]
Remove restrictions on TypeName and tag value Name
