### ISSUE TITLE
When a new configuration object is created, Format is in Chinese

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#395]
新建配置对象，英文状态下，“格式”仍是中文
![image](https://user-images.githubusercontent.com/95004531/224263581-915c6cbc-bac7-41ab-a495-00679b969e1f.png)

**Comment by MapleWithoutWords** [comment]
![image](https://user-images.githubusercontent.com/38368335/224603228-f6f1537e-8f8f-4b64-a4df-3790e206959d.png)
