### ISSUE TITLE
properties format configuration object. The scroll bar of the table should not contain the table header

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#398]
properties格式配置对象，表格的滚动条应不包含表头
![image](https://user-images.githubusercontent.com/95004531/224267962-2bba6cb5-78a4-4f2e-a534-9c0a16d0c967.png)

**Comment by MayueCif** [comment]
固定表头

**Comment by MapleWithoutWords** [comment]
already resolved:https://github.com/masastack/MASA.DCC/pull/408
