### ISSUE TITLE
After the rollback, the auto-populated description does not have i18n

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#400]
回滚后的发布历史，自动填充的描述没有i18n
![image](https://user-images.githubusercontent.com/95004531/224272537-aa01310a-3c4c-4c67-b886-42c9683b2af9.png)

**Comment by MapleWithoutWords** [comment]
@MayueCif the description content is a ```comment``` field,it storage in database
![image](https://user-images.githubusercontent.com/38368335/224294252-1a9116ad-f7cc-4a11-a536-a936dde62544.png)
