### ISSUE TITLE
Configure the details page, switch clusters, and reset the status of the extension panel.

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#403]
配置详情页，切换集群，扩展面板应重置状态。
目前有的状态被重置，有的状态没有被重置。

https://user-images.githubusercontent.com/95004531/224284533-a6558a81-1bcc-47f5-a2d1-d174b3dade25.mp4

**Comment by MapleWithoutWords** [comment]
already resolved :https://github.com/masastack/MASA.DCC/pull/404
