### ISSUE TITLE
Tag management, add the tag value of the row, directly to the form validation

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#406]
标签管理，添加标签值的行后，直接进行表单验证，应在鼠标移入输入框再点击输入框外，或者点击保存按钮时进行表单验证
![image](https://user-images.githubusercontent.com/95004531/224297857-40432800-d78d-4cb3-9026-506c8aa128a4.png)

**Comment by zyz** [comment]
Development environments do not have this issues

**Comment by LazyEar0** [comment]
site is staging
