### ISSUE TITLE
For label management, TypeName and TypeCode must be unique

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#410]
标签管理，新建标签，输入已存在的TypeCode提交表单，会覆盖已存在TypeCode的标签名称。提交表单时，应验证TypeCode是否重复，如已存在，则不可提交
![image](https://user-images.githubusercontent.com/95004531/224592535-4c15034c-89d6-4f45-a417-b411a5f1bc85.png)

**Comment by kogel-net** [comment]
#416
