### ISSUE TITLE
Global.When you close the edit popup, "Edit XXX" in the upper left corner will change to "Add XXX".

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#411]
关闭编辑弹窗时，左上角的“编辑XXX”，会变为“新增XXX”
![image](https://user-images.githubusercontent.com/95004531/224592664-1ea6175e-3967-4f3d-8c17-e785fd28d1e5.png)

**Comment by kogel-net** [comment]
#440
