### ISSUE TITLE
Configure the details page and click the "Edit" button to automatically expand the extension panel when the extension panel is folded

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#431]
配置详情页，扩展面板收起时，点击“编辑”按钮，自动展开该扩展面板
![image](https://user-images.githubusercontent.com/95004531/225526680-96a1a939-9bf1-4330-8f57-1216cd441982.png)
实际效果：
![image](https://user-images.githubusercontent.com/95004531/225526822-411c3c45-7112-4be5-91c4-09ff3d07a5ec.png)
预期结果：
点击“编辑”按钮后，自动展开扩展面板，鼠标自动定位到文本框
![image](https://user-images.githubusercontent.com/95004531/225527012-a45c0773-8198-4f01-89e8-827798382352.png)

**Comment by zyz** [comment]
#452  Configuration details page, Click the Edit button to expand the extension panel automatically

**Comment by LazyEar0** [comment]
引发  #460
