### ISSUE TITLE
Clone the configuration object. The first application cannot be selected directly

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#432]
克隆配置对象 - 选择克隆至其他应用 - 选择项目
实际结果：
选择项目后，选择APP下拉框第一个，不显示选中的APP。切换其他APP后，再选回第一个，正常显示
![image](https://user-images.githubusercontent.com/95004531/225528091-0a01d3e4-0ef8-4c10-95a9-f03f992c088a.png)
预期结果：
选择项目后，APP会默认选中第一个
![image](https://user-images.githubusercontent.com/95004531/225529061-261f0bba-ad1c-4c43-9aab-d10ed41f329b.png)

**Comment by kogel-net** [comment]
#439
