### ISSUE TITLE
Clone a configuration object. Expand the cloned configuration object and automatically collapse the configuration object after it is modified

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#436]
克隆配置对象，展开克隆的配置对象，修改配置信息后会自动收起

https://user-images.githubusercontent.com/95004531/225538401-de91e91d-3b19-47b6-a095-7121e20c79ba.mp4

**Comment by MayueCif** [comment]
应该是组件问题 联系曹优先确认

**Comment by zyz** [comment]
#456 Fix: ExpansionPanel auto collapse
