### ISSUE TITLE
When there are no projects and applications, the default page is not needed for the time being

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#442]
没有项目和应用时，暂时不需要缺省页。等后期UI设计后，所有项目统一更换
![image](https://user-images.githubusercontent.com/95004531/225842253-0d55fcae-72f9-41b3-8ac2-339869db7db4.png)
![image](https://user-images.githubusercontent.com/95004531/225842288-235f6a44-e2b0-4d56-8a73-1249d9db95ea.png)
![image](https://user-images.githubusercontent.com/95004531/225842334-09761f43-86a1-4435-b00d-c2c6020afeaa.png)

**Comment by kogel-net** [comment]
#416

**Comment by MayueCif** [comment]
SEmptyPlaceholder 缺省页展位组件
