### ISSUE TITLE
Label management, new pop-up window display error

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#444]
标签管理，新建弹窗显示错误
步骤：
1.点击编辑按钮，进入编辑标签弹窗
2.关闭编辑标签弹窗
3.点击新建按钮，打开新建标签弹窗
实际结果：
打开的是编辑弹窗
![image](https://user-images.githubusercontent.com/95004531/226262352-6f955337-e761-4c91-9f1d-f453ed0a3823.png)

预期结果：
应打开新建弹窗。（P.s. 新建弹窗左上角标题，由“新增标签”改为“新建标签”）
![image](https://user-images.githubusercontent.com/95004531/226262158-09a426df-1052-4ce8-ada9-5bc132619aba.png)

**Comment by kogel-net** [comment]
#449
