### ISSUE TITLE
Edit label, label value data duplicate

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#446]
编辑标签，标签值数据重复
操作步骤：
1.新建标签，输入数据，点击提交按钮
![image](https://user-images.githubusercontent.com/95004531/226266997-9dce689b-0bed-49df-86c1-c4ec484bd7fc.png)
2.点击编辑标签按钮，进入编辑标签弹窗
![image](https://user-images.githubusercontent.com/95004531/226267110-335f1986-c743-4ef2-8097-645aea7ae6ca.png)
实际结果：
标签值数据重复
![image](https://user-images.githubusercontent.com/95004531/226267164-d72f8bc2-c349-4a7f-a93a-6703018a4248.png)
预期结果：
标签值数据应与新建时保持一致

**Comment by kogel-net** [comment]
等待组件更新解决
