### ISSUE TITLE
Encrypted configuration objects clicking on publication history and rollback will give an error

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#513]
加密的配置对象点击发布历史和回滚会报错
![image](https://user-images.githubusercontent.com/95004531/229442364-a21eda72-786a-4962-9bd4-c8d5161b9c97.png)

**Comment by zyz** [comment]
Automatic normal

**Comment by LazyEar0** [comment]
此问题再次出现
![image](https://user-images.githubusercontent.com/95004531/236383320-e08a0677-8f88-4c4b-a2be-066792dd2d83.png)

**Comment by zyz** [comment]
Add log update system automatically normal, development environment and local environment cannot be reproduced
