### ISSUE TITLE
Once the user enters the project team, the page keeps loading

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#527]
当前登录用户，如没有在项目团队中，但是有左侧菜单“项目团队”的权限。用户进入项目团队后，页面一直loading，应显示没有数据（PM同样存在此问题，一并修复后，将此问题标记为已解决，不再重复提issue）
![image](https://user-images.githubusercontent.com/95004531/231098917-9fd0d8d8-a939-4d8a-9cdb-8c605ab2c8d0.png)

**Comment by zyz** [comment]
#529 
https://github.com/masastack/MASA.PM/pull/342

**Comment by LazyEar0** [comment]
DCC 当前登录用户没有项目团队，进入团队页面的文本需要调整
![image](https://user-images.githubusercontent.com/95004531/231663583-0311d4ef-976b-4ec1-ae77-61017a768dd5.png)

**Comment by zyz** [comment]
https://github.com/masastack/MASA.DCC/pull/534
