### ISSUE TITLE
In the English state, there are modifications to the label width to adjust

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#575]
英文状态下，有修改标签宽度需要调整
![image](https://github.com/masastack/MASA.DCC/assets/95004531/80b2c077-9bdd-454c-94ff-6388c4441884)

**Comment by limei7** [comment]
![image](https://github.com/masastack/MASA.DCC/assets/93168234/14bd1cd0-553d-49e4-85ff-1e7256ddebc7)
