### ISSUE TITLE
不同环境或集群，同一个项目对应的团队是不一样的， 左侧导航显示的团队是空

### ISSUE THREAD

**Issue by limei7** [masastack/MASA.DCC#624]
![image](https://github.com/masastack/MASA.DCC/assets/93168234/2faeaf06-a345-4717-a015-c1371ff3909b)

**Comment by codding-y** [comment]
暂时显示登录人当前环境的团队

**Comment by limei7** [comment]
![image](https://github.com/masastack/MASA.DCC/assets/93168234/ff2dd308-e873-45c7-a403-9f74f07a1280)
retest ok
