### ISSUE TITLE
Biz Configuration Details，The function of modifying the service configuration name is missing

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#70]
业务配置详情，缺少修改业务配置名称功能；

![image](https://user-images.githubusercontent.com/95004531/174017534-08d51e69-1f74-497a-907b-447f3efe2bb6.png)

**Comment by codding-y** [comment]
上一步可修改

**Comment by LazyEar0** [comment]
业务配置详情暂无修改名称功能
