### ISSUE TITLE
Configuration details，Open the menu and slide the mouse. The position of the menu does not change

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.DCC#96]
实际结果：
打开更多菜单后，页面的滚动条可滑动，且菜单的位置固定不变；

预期结果：
打开更多菜单后，滑动鼠标时，菜单弹窗的位置随着滚动条变化；

![image](https://user-images.githubusercontent.com/95004531/174212840-b0cf01a4-21f1-4aab-8e6c-ab26aedbc174.png)

**Comment by codding-y** [comment]
@capdiem
